/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webrtc_audioprocessing_Aec3 */

#ifndef _Included_com_webrtc_audioprocessing_Aec3
#define _Included_com_webrtc_audioprocessing_Aec3
#ifdef __cplusplus
extern "C"
{
#endif
        /*
         * Class:     com_webrtc_audioprocessing_Apm
         * Method:    nativeCreateApmInstance
         * Signature: (ZZZZZZZ)Z
         */
        JNIEXPORT jboolean JNICALL Java_com_webrtc_audioprocessing_Apm_nativeCreateApmInstance(JNIEnv *, jobject, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

        /*
         * Class:     com_webrtc_audioprocessing_Apm
         * Method:    nativeFreeApmInstance
         * Signature: ()V
         */
        JNIEXPORT void JNICALL Java_com_webrtc_audioprocessing_Apm_nativeFreeApmInstance(JNIEnv *, jobject);

        /*
         * Class:     com_webrtc_audioprocessing_Apm
         * Method:    ProcessStream
         * Signature: ([SI)I
         */
        JNIEXPORT jint JNICALL Java_com_webrtc_audioprocessing_Apm_ProcessStream(JNIEnv *, jobject, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif